name: BTC Balance Checker

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Manual trigger

jobs:
  check-balance:
    runs-on: ubuntu-latest
    env:
      BTC_ADDRESS: ${{ secrets.BTC_ADDRESS }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          [ -n "$BTC_ADDRESS" ] && echo "BTC_ADDRESS set? set (masked)" || echo "BTC_ADDRESS unset"
          [ -n "$EMAIL_SENDER" ] && echo "EMAIL_SENDER set? set (masked)" || echo "EMAIL_SENDER unset"
          [ -n "$EMAIL_PASSWORD" ] && echo "EMAIL_PASSWORD set? set (masked)" || echo "EMAIL_PASSWORD unset"
          [ -n "$EMAIL_RECIPIENT" ] && echo "EMAIL_RECIPIENT set? set (masked)" || echo "EMAIL_RECIPIENT unset"

      - name: Run balance check script
        run: python main.py
